### ISSUE TITLE
Bug with Fasta-Parser

### ISSUE THREAD

**Issue by greatfireball** [BioInf-Wuerzburg-teaching/teaching-Fasta-Parser#1]
Dear Thomas,

Your script performs a Dumper output for each loop plus an additional output after looping through the Fasta-File. I suggest to remove the print Dumper statement in line 15.

Best regards,
Frank

**Comment by thackl** [comment]
Dear Frank,

could you please provide me with the FASTA file you are using.

Cheers
Thomas
